apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: java-hello-world
 annotations: {}
 labels: {}
description: Deploys the java-hello-world

serialPipeline:
 stages:
 - targetId: dev
   profiles: [dev]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev
 annotations: {}
 labels: {}
description: st cluster
requireApproval: false
gke:
 cluster: projects/sapient-mariner-346422/locations/us-central1/clusters/om-cluster-1
 internalIp: true
executionConfigs:
- privatePool:
    workerPool: projects/sapient-mariner-346422/locations/us-central1/workerPools/default-pool
    serviceAccount: java-hello-world@sapient-mariner-346422.iam.gserviceaccount.com
  usages:
  - DEPLOY
- defaultPool:
    serviceAccount: java-hello-world@sapient-mariner-346422.iam.gserviceaccount.com
  usages:
  - RENDER